### ISSUE TITLE
No such file or directory: './text_prompt/kitti_ViT16_clip_text_p.pth'

### ISSUE THREAD

**Issue by LISI0037** [youquanl/M3Net#2]
Thank you for your great work! But when I try to do the training, I met some problem. 
```
Traceback (most recent call last):
  File "/users/.conda/envs/m3net/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/users/baseline_dataset/M3Net/exp/semantickitti/testtest_m3net/code/pointcept/engines/launch.py", line 131, in _distributed_worker
    main_func(*cfg)
  File "/users/baseline_dataset/M3Net/exp/semantickitti/testtest_m3net/code/tools/train.py", line 15, in main_worker
    trainer = TRAINERS.build(dict(type=cfg.train.type, cfg=cfg))
  File "/users/baseline_dataset/M3Net/exp/semantickitti/testtest_m3net/code/pointcept/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/users/baseline_dataset/M3Net/exp/semantickitti/testtest_m3net/code/pointcept/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: MultiDatasetTrainer: MultiSpaceTraining: [Errno 2] No such file or directory: './text_prompt/kitti_ViT16_clip_text_p.pth'
```
I don't know how to get `kitti_ViT16_clip_text_p.pth`, and the README doesn't explain how to obtain this file.
Can you help me with it?

**Comment by youquanl** [comment]
Hello @LISI0037,

I sincerely apologize for any inconvenience caused. The missing files are now attached [here](https://github.com/youquanl/M3Net/tree/main/generation/text_prompt). Additionally, you can refer to [this link](https://github.com/runnanchen/CLIP2Scene/blob/main/utils/prompt_engineering.py) and the supplementary materials for more detailed information on text prompts. I will be updating the related information soon.

**Comment by LISI0037** [comment]
Thanks for the quick reply!！
And I met another error, could you give me some advice? 
Because I don't need to use client so I use 
`sam_feature = torch.tensor(np.fromfile(sam_feature_path, dtype=np.float32).reshape(1, 256, 64, 64))` 
to replace 
`sam_feature = torch.tensor(np.frombuffer(client.get(sam_feature_path), dtype=np.float32).reshape(1, 256, 64, 64))`. 
And I think they have the same effect. But I got the error: 
`ValueError: cannot reshape array of size 1048617 into shape (1,256,64,64)`. 
And same things happened: 
`img_logit = torch.tensor(np.fromfile(img_logits_path, dtype=np.float32).reshape(-1, 19))`
`ValueError: cannot reshape array of size 395506 into shape (19)`. 
I obtained both sam_feature and img_logit by strictly following the instructions in your README(using SAM and OpenSeeD). Do you have any ideas about this error? (And the file which give error is : /M3Net/pointcept/datasets/semantic_kitti.py)
